### ISSUE TITLE
Should this repo be archived?

### ISSUE THREAD

**Issue by vdice** [fermyon/rust-docs#1]
Now that Spin Rust docs are published to https://docs.rs/spin-sdk/latest/spin_sdk/ via https://github.com/fermyon/spin-rust-sdk, should this repo be archived?

If so, we should also remove [the CI in Spin that triggers workflows in this repo](https://github.com/fermyon/spin/blob/main/.github/workflows/dispatch.yml)

cc @lann

**Comment by lann** [comment]
This also publishes internal spin docs but has apparently been broken for a while. I will fix it.

**Comment by lann** [comment]
https://fermyon.github.io/rust-docs/spin/main/
